#!/usr/bin/env python3
"""Export the risk model for the box, and check the export against Python.

The risk model is the other half of the project: the polisher corrects a strand after the
channel, this one predicts, before anything is written, how likely a strand is to come back
wrong. On the box there is no encoder for it to steer, so it is shown instead: every strand
on the tape carries the risk this model gives it.

It is small, 63,797 parameters and about 6.4M multiply accumulates per strand, so it runs in
float32 on the chip. Quantizing it would save flash that is not scarce and cost accuracy
that is, which is why only the polisher is int8.

Two things are folded away at export time:
  BatchNorm      folded into the convolution in front of it, which is exact at inference
  the mask       the input is zero beyond the strand's length and every block multiplies by
                 the mask, so the tensor past the end is zero at every stage. Running at the
                 strand's own length gives the same answer as padding to 140 and masking.

    uv run python hardware/esp32_ticker/tools/export_risk.py --write ../src/box_risk_weights.h
"""

from __future__ import annotations

import argparse
import pickle
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

CKPT = REPO_ROOT / "checkpoints" / "risk" / "risk_nanopore_budget.pkl"


def load(path: Path):
    with Path(path).open("rb") as f:
        return pickle.load(f)


def fold_bn(w, b, gamma, beta, mean, var, eps=1e-5):
    """Fold a BatchNorm that follows a convolution into that convolution's weights."""
    scale = gamma / np.sqrt(var + eps)
    return w * scale[:, None, None], (b - mean) * scale + beta


def export(model):
    sd = {k: v.detach().cpu().numpy().astype(np.float64) for k, v in model.net.state_dict().items()}
    out = {}
    out["stem.weight"] = sd["stem.weight"]
    out["stem.bias"] = sd["stem.bias"]
    n_blocks = model.config["n_blocks"]
    for i in range(n_blocks):
        w, b = fold_bn(
            sd[f"blocks.{i}.conv1.weight"], sd[f"blocks.{i}.conv1.bias"],
            sd[f"blocks.{i}.norm.weight"], sd[f"blocks.{i}.norm.bias"],
            sd[f"blocks.{i}.norm.running_mean"], sd[f"blocks.{i}.norm.running_var"],
        )
        out[f"b{i}.conv1.weight"] = w
        out[f"b{i}.conv1.bias"] = b
        out[f"b{i}.conv2.weight"] = sd[f"blocks.{i}.conv2.weight"]
        out[f"b{i}.conv2.bias"] = sd[f"blocks.{i}.conv2.bias"]
    out["head0.weight"] = sd["head.0.weight"]
    out["head0.bias"] = sd["head.0.bias"]
    out["head1.weight"] = sd["head.3.weight"]
    out["head1.bias"] = sd["head.3.bias"]
    return out


def write_header(path: Path, tensors: dict, channels: int, n_blocks: int) -> None:
    lines = []
    w = lines.append
    w("// Generated by hardware/esp32_ticker/tools/export_risk.py. Do not edit by hand.")
    w("//")
    w("// The risk model: a small CNN over one-hot bases that predicts how likely a strand is")
    w("// to come back wrong. float32, BatchNorm already folded into the convolution in front")
    w("// of it. Convolution weights are stored as [out][tap][in] so the inner product over")
    w("// input channels is contiguous.")
    w("")
    w("#pragma once")
    w("#include <stdint.h>")
    w("")
    w(f"#define RISK_CHANNELS {channels}")
    w(f"#define RISK_BLOCKS {n_blocks}")
    w("#define RISK_IN 6        // one hot A C G T, the mask, the relative position")
    w("#define RISK_STEM_K 9")
    w("#define RISK_CONV1_K 5")
    w("")

    def emit(name, arr, transpose=False):
        a = np.asarray(arr)
        if transpose and a.ndim == 3:
            a = np.transpose(a, (0, 2, 1))  # [out][in][k] -> [out][tap][in]
        flat = a.reshape(-1).astype(np.float32)
        w(f"static const float {name}[{flat.size}] = {{")
        for i in range(0, flat.size, 8):
            w("  " + ",".join(f"{float(v):.8g}f" for v in flat[i : i + 8]) + ",")
        w("};")

    emit("kR_stem_w", tensors["stem.weight"], transpose=True)
    emit("kR_stem_b", tensors["stem.bias"])
    for i in range(n_blocks):
        emit(f"kR_b{i}_c1w", tensors[f"b{i}.conv1.weight"], transpose=True)
        emit(f"kR_b{i}_c1b", tensors[f"b{i}.conv1.bias"])
        emit(f"kR_b{i}_c2w", tensors[f"b{i}.conv2.weight"], transpose=True)
        emit(f"kR_b{i}_c2b", tensors[f"b{i}.conv2.bias"])
    emit("kR_h0w", tensors["head0.weight"])
    emit("kR_h0b", tensors["head0.bias"])
    emit("kR_h1w", tensors["head1.weight"])
    emit("kR_h1b", tensors["head1.bias"])
    path = Path(path)
    if not path.is_absolute():
        path = (HERE / path).resolve()
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path} ({path.stat().st_size / 1024:.0f} KB)")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--checkpoint", default=str(CKPT))
    ap.add_argument("--write", default=None)
    args = ap.parse_args(argv)

    model = load(Path(args.checkpoint))
    tensors = export(model)
    total = sum(v.size for v in tensors.values())
    print(f"risk model: {model.config}, {total} exported parameters")
    if args.write:
        write_header(Path(args.write), tensors, model.config["channels"],
                     model.config["n_blocks"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
